### PR TITLE
remove path/query join

### PR DESCRIPTION
**Pull request by X4mp**
fixed an issue where files could not be served if requested with a url parameter

### CODE REVIEW

**Comment by afeena** [comment]
Sometimes links can have the form such as ``foo.com/?p=1`` (e.g. on wp sites). In this case query part makes sense. It should be fixed in the cloner.

I've started some initial work [here ](https://github.com/afeena/snare/commit/075d4e8cce608abcd4260d77381fea6edb0f8d42) , but it should be tested carefully.

**Comment by X4mp** [comment]
reopen for review

**Comment by afeena** [comment]
We can keep these changes until we fix cloner

**Comment by glaslos** [comment]
@afeena feel free to merge when you are happy with the PR

**Pull request merged**
