### PR TITLE
Added more tests and Pep8 fixes

### PR DESCRIPTION
**Pull request by lordlabuckdas**
* Added more tests and fixed some existing ones

* Coverage increased from 65% to 91% (tested locally with pytest)

* Pep8 fixes to the whole repo

Edit:

* Fixed long strings to comply with pep8

* Changed permissions of 2 test files (from 755 to 644), they were skipped in testing because of executable permissions

* Changed format-strings to string concatenation to add python3.5 support

Ref #187

### CODE REVIEW

**Comment by glaslos** [comment]
> Fixed long strings to comply with pep8

@afeena or @viskey98 do you remember what line length we accept? I don't think we go strict pep8 (I also disagree with the 80 chars).

**Comment by lordlabuckdas** [comment]
@glaslos, Travis CI's `pycodestyle` has `--max-line-length 120`. So, if that's the max character length, I'll reformat my branch to comply with it.

**Comment by glaslos** [comment]
@lordlabuckdas that sounds about right 👍

**Review by glaslos — APPROVED** [review]
LGTM. Nice work and thanks for adding tests and cleaning the code!

**Comment by afeena** [comment]
Thanks @lordlabuckdas :) looks great!

**Comment by lordlabuckdas** [comment]
Glad I could be of help 😄

**Pull request merged**
