### PR TITLE
Test get_dorks

### PR DESCRIPTION
**Pull request by viskey98**
This PR will test get_dorks by checking if the get_dorks() function (of snare.py) was able to connect to default tanner and get dorks.

### CODE REVIEW

**Comment by afeena** [comment]
What are you actually testing here? If you want to test that you get exception when server is not available, use assertRaise https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaises

**Comment by viskey98** [comment]
I am trying to make sure no exception occurs when I run that function. assertRaises will assert if the exception occurs and will pass the test for the same. But I wish to fail the test in case of any exception regarding the connection and pass otherwise. That is why I didn't use assertRaises.

**Comment by viskey98** [comment]
I have re-written the test by implementing :
- test_get_dorks: testing if get_dorks returns a empty list '[]' without raising any exception.

- test_get_dorks_fail: testing if get_dorks fails with a non-existent server by raising a specified exception.

**Comment by viskey98** [comment]
@afeena I have re-written the test (using mocks) by testing follwing behaviour:
- test_get_dorks: to check if the session.get() was called with correct parameters
- test_return_dorks: to check if dorks obtained from ClientSession.json() is returned properly.
- test_return_dorks_exception: to check if the exception occuring in the function is raised properly.

**Pull request merged**
