### PR TITLE
Fix #6 

### LINKED ISSUE #6: Server header
We should either not provide a server header or use one provided by the user.

### PR DESCRIPTION
**Pull request by rnehra01**
Add an argument to take input `Server-header` and set its default value to `'None'` so that the server sends `'None'` if no input is provided

### CODE REVIEW

**Comment by afeena** [comment]
Why do you choose None as a default value? Maybe it is more reasonable to send something very common as a default not to capture the attention? (e.g. nginx). I'm not an expert, but if I were a bad guy, I would be very interested about None server value

**Comment by rnehra01** [comment]
Okay, sounds good to me, I'll add nginx as default.

**Comment by afeena** [comment]
Looks good, thanks for the pr :)

**Comment by glaslos** [comment]
@afeena feel free to merge when you are happy with the PR

**Comment by afeena** [comment]
@glaslos Ok, thanks :)

**Pull request merged**
