### PR TITLE
Updated the cloner docs

### PR DESCRIPTION
**Pull request by sanskar11**
Updated the cloner docs and removed the blank line from setup.py

### CODE REVIEW

**Review by mzfr — CHANGES_REQUESTED** [review]
@sanskar11 You created 3 PR #285, #286, and #287 but all 3 have the same changes. I think you can close #285 and #286

**Comment by sanskar11** [comment]
@mzfr #285 build failed because of there was a blank line issue which I corrected in #286. Therefore I made #287 in which I made both the changes.

**Review by glaslos — APPROVED** [review]
LGTM

**Comment by glaslos** [comment]
Thank you @sanskar11 for fixing testing :muscle:

**Pull request merged**
