### PR TITLE
Using pythongit to auto-update

### PR DESCRIPTION
**Pull request by afeena**

### CODE REVIEW

**Comment by glaslos** [comment]
You have to update the requirements.txt file. Do you think we can bring this to the next level and check for updates every x hours?

**Comment by afeena** [comment]
I think we can :) How often?

**Comment by glaslos** [comment]
Make it a parameter with a sensible default value :)

**Comment by afeena** [comment]
After some attempts and failures I have: 

- If we have loop, or any repeatable code for updates in snare, it can't update after first time because of snare drop privileges and repo can't be update:
```
git.exc.GitCommandError: 'git fetch -v origin' returned with exit code 255 
stderr: 'error: cannot open .git/FETCH_HEAD: Permission denied
```
- If we will have separate file for updates and run it as a subprocess, we need some kind of communication and the possibility to restart snare script from root if we have updates. 

Can you please give me advice how it would be better to organize updates?

**Comment by glaslos** [comment]
Have you looked into forking the process so you have one with elevated permissions?

**Comment by afeena** [comment]
I thought about it. Thanks, I'll try it :)

**Comment by glaslos** [comment]
Well done!

**Pull request merged**
